<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- Exclude the output of source generators from the compilation, show it in the IDE -->
    <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    <None Include="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="Ulid" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
